from models.data.ControlFeedbackState import ControlFeedbackState
from models.wind.WindProfileBuilder import SpectralContent
from models.wind.WindProfileBuilder import Vel
from models.data.ProbeFeedbackState import ProbeFeedbackState

import math
import numpy as np

class TurbulenceSpectralControl():
    """Class which controls sine amplitudes based on total turbulence PWM setting within ControlFeedbackState: Takes user inputs to generate
    custom spectral peaks, if no peaks will generate a uniform discrete spectrum distribution"""
    def __init__(self):
        # Spectral amplitude adjustment controller (12 controllers)
        self.KP = 30
        self.KI = 0
        self.KD = 0
        self.TAU = 20

        self.FQ_ATTENUATION_COMPENSATION_FACTOR = 1

        self.statistics = SpectralAmplitudeStats(self._get_frequency_list(), self.TAU, dt = 0.01)

    def update(self) -> None:
        current_velocity = self._get_probe_windspeed()
        self.statistics.update(current_velocity, ControlFeedbackState.dt)
        new_rel_amplitudes = {}
        for sines in ControlFeedbackState.frequency_band_sines:
            if sines is not None:
                target = sines.target_amplitude
                measurement = self.statistics.relative_amplitude(sines.frequency)
                controller = sines.controller
                raw_amplitude_correction = controller.update(target, measurement, ControlFeedbackState.dt)
                new_rel_amplitudes[sines.frequency] = (raw_amplitude_correction + sines.amplitude) #*(sines.frequency-0.05)/0.05*self.FQ_ATTENUATION_COMPENSATION_FACTOR
                # if sines.frequency == 0.6 or sines.frequency == 0.05:
                #     print(f"SINE FQ: {sines.frequency}, TARGET REL A: {sines.target_amplitude:.3f}, ACTUAL REL A: {measurement:.3f}, REL AMP INSTR: {raw_amplitude_correction + sines.amplitude}")

        total_turbulence_pwm = ControlFeedbackState.baseline_turbulence_pwm + ControlFeedbackState.correction_turbulence_pwm
        # Ensures total control action is distributed such that total turbulence is unchanged
        total_relative_amplitude = np.sqrt(sum(amplitude**2 for amplitude in new_rel_amplitudes.values()))
        amplitude_ratio = total_turbulence_pwm / total_relative_amplitude
        print(
    "TOTAL PWM:", total_turbulence_pwm,
    "VECTOR RMS:", total_relative_amplitude * amplitude_ratio,
    "AMPLITUDES:",
    {round(k, 2): round(v, 2)
     for k, v in new_rel_amplitudes.items()}
)

        for sines in ControlFeedbackState.frequency_band_sines:
            if sines is not None:
                sines.update_amplitude(new_rel_amplitudes[sines.frequency] * amplitude_ratio)

    def refresh_controller(self):
        self._assign_sine_controllers()
        if hasattr(ControlFeedbackState, 'target_spectral_content'):
            ControlFeedbackState.set_target_spectrum()
        else:
            ControlFeedbackState.set_target_spectrum(self._generate_uniform_spectral_instr())

    def _assign_sine_controllers(self):
        for sines in ControlFeedbackState.frequency_band_sines:
            if sines is not None:
                sines.set_controller(self.KP, self.KI, self.KD)

    def _generate_uniform_spectral_instr(self):
        frequency_list = self._get_frequency_list()
        new_spectrum = SpectralContent(frequency_amplitude_dict={})
        for fq in frequency_list:
            new_spectrum.frequency_amplitude_dict[fq] = 1
        return new_spectrum

    def _get_frequency_list(self):
        frequency_list = []
        for sines in ControlFeedbackState.frequency_band_sines:
            if sines is not None:
                frequency_list.append(sines.frequency)
        return frequency_list

    def _get_probe_windspeed(self) -> float:
        v_component = ControlFeedbackState.velocity_component
        if v_component == Vel.X:
            return ProbeFeedbackState.windspeed_x
        if v_component == Vel.Y:
            return ProbeFeedbackState.windspeed_y
        if v_component == Vel.Z:
            return ProbeFeedbackState.windspeed_z

class SpectralAmplitudeStats:
    """Exponential Moving Average of amplitudes at each frequency of interest, 
    uses cosine and sine functions to estimate amplitude at each specified frequency by fitting them to the signal on a rolling basis."""
    # NOTE: Mathematics generated by AI 
    def __init__(self, frequencies, tau, dt):
        self.frequencies = frequencies
        self.dt = dt
        self.tau = tau
        self.alpha = math.exp(-dt / tau)

        self.cos = {frequency: 0.0 for frequency in frequencies}
        self.sin = {frequency: 0.0 for frequency in frequencies}
        self.time = 0.0
        self.initialised = False

    def update(self, x, dt):
        self.dt = dt
        self.alpha = math.exp(-dt / self.tau)

        if math.isnan(x):
            self.time += dt
            return

        for frequency in self.frequencies:
            phase = 2 * math.pi * frequency * self.time

            self.cos[frequency] = (
                self.alpha * self.cos[frequency]
                + (1 - self.alpha) * x * math.cos(phase)
            )

            self.sin[frequency] = (
                self.alpha * self.sin[frequency]
                + (1 - self.alpha) * x * math.sin(phase)
            )

        self.time += dt
        self.initialised = True

    def amplitude(self, frequency):
        if not self.initialised:
            return 0.0

        cos_component = self.cos[frequency]
        sin_component = self.sin[frequency]

        return 2 * math.sqrt(
            cos_component**2 + sin_component**2
        )

    def relative_amplitude(self, frequency):
        amplitudes = {
            f: self.amplitude(f)
            for f in self.frequencies
        }

        total = math.sqrt(
            sum(amplitude**2 for amplitude in amplitudes.values())
        )

        if total == 0:
            return 0.0

        return amplitudes[frequency] / total